// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlYtQ0nqY0a3DBNs7HFBJ6m6JPqoJaAlM',
    appId: '1:393126444127:web:66e49c53c8a0eb60496fea',
    messagingSenderId: '393126444127',
    projectId: 'lopako-4488a',
    authDomain: 'lopako-4488a.firebaseapp.com',
    storageBucket: 'lopako-4488a.firebasestorage.app',
    measurementId: 'G-PB1TRH1892',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWT5DIJEOfHeyfNSkolo_VD484bewQg4o',
    appId: '1:393126444127:android:a9cb9b0c1830018b496fea',
    messagingSenderId: '393126444127',
    projectId: 'lopako-4488a',
    storageBucket: 'lopako-4488a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEBFENvxKOq-wjSq2JmrY7edE4B1Wc2Qw',
    appId: '1:393126444127:ios:5981c7e360279157496fea',
    messagingSenderId: '393126444127',
    projectId: 'lopako-4488a',
    storageBucket: 'lopako-4488a.firebasestorage.app',
    iosClientId: '393126444127-t117j48ab1mqk1kmbhi4llntk17ih4g6.apps.googleusercontent.com',
    iosBundleId: 'com.lopako.lopakoAppLis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEBFENvxKOq-wjSq2JmrY7edE4B1Wc2Qw',
    appId: '1:393126444127:ios:cfd3b4bcc6a772a9496fea',
    messagingSenderId: '393126444127',
    projectId: 'lopako-4488a',
    storageBucket: 'lopako-4488a.firebasestorage.app',
    iosClientId: '393126444127-9hdc8oiat7v6i6vtuggaur5aseto1kj5.apps.googleusercontent.com',
    iosBundleId: 'n',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlYtQ0nqY0a3DBNs7HFBJ6m6JPqoJaAlM',
    appId: '1:393126444127:web:f20bd02cf87cba4c496fea',
    messagingSenderId: '393126444127',
    projectId: 'lopako-4488a',
    authDomain: 'lopako-4488a.firebaseapp.com',
    storageBucket: 'lopako-4488a.firebasestorage.app',
    measurementId: 'G-BEQKQ5KNZS',
  );

}